### ISSUE TITLE
Package `zfind` instead of `hugo`

### ISSUE THREAD

**Issue by brenthuisman** [brenthuisman/par2cmdline-turbo-python-distributions#1]
https://github.com/laktak/zfind

**Comment by agriyakhetarpal** [comment]
Hi there, I noticed that you forked my project – thanks! I would say that my code for packaging Go binaries/executables with Python isn't the best out there, and though I haven't spent time refactoring my original implementation, it works perfectly for now. I hope that my in-line comments inside the packaging code will be useful to you. Please feel free to open an issue if you find something that can be improved or if there's a bug I haven't noticed. I am considering migrating to [`hatch`](https://hatch.pypa.io/latest/build/) and [`hatch-build-scripts`](https://github.com/rmorshea/hatch-build-scripts) someday, but I am not sure how I would navigate setting the platform tag in that case – which I currently do by subclassing `bdist_wheel`, and that integrates with `setuptools` quite well.

**Comment by brenthuisman** [comment]
Thanks for the heads up! You did document very well, but it was a little less simple than I hoped. Also, setuptools :) I'll see if and when I have time though, but being able to package and post to PyPI non-python utilities is an interesting and useful use case for me.

**Comment by agriyakhetarpal** [comment]
I'm planning to push some code over the weekend that should make following along the build process easier. The code uses a few Go and Hugo-specific assumptions, but that's mostly because I never planned (or plan) to distribute this as a PEP 517 style build backend for other users. I'll be happy to help you out in any way I can – I do not know how `zfind` works, but if you don't need a C compiler (`CGO_ENABLED`=`0`) to build it, that simplifies things a bit.

**Comment by brenthuisman** [comment]
`zfind` is pure Go, and indeed that was the other part of the attempt: see if it's easy to wrap such projects and provide through PyPI.
